{
 "title": "Alluxio AI Enterprise Edition Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ready Workers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(Worker_Client_CacheState / 2))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cached Space Available",
   "type": "stat",
   "description": "Total number of pages in the client cache",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Worker_Client_CacheSpaceAvailable)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Space Used",
   "type": "stat",
   "description": "Total number of pages in the client cache",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Worker_Client_CacheSpaceUsed)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$C / ( $C + $U )", "type": "math" }
   ]
  },
  { "title": "Cost Saving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GetFileInfo Hit",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Worker_GetFileInfoHitRequests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ListStatus Hit",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Worker_ListStatusHitRequests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Cache Hit",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Worker_Client_CacheHitRequests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AWS S3 API Cost Without Alluxio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($A + $B + $E) / 1000 * 0.0004 + ($C + $F) / 1000 * 0.005",
     "type": "math"
    }
   ]
  },
  {
   "title": "AWS S3 Cost With Alluxio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($A + $B) / 1000 * 0.0004 + $C / 1000 * 0.005",
     "type": "math"
    }
   ]
  },
  {
   "title": "AWS S3 Cost Saving",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($A+$B) * 0.0004/1000 + $C / 1000 * 0.005",
     "type": "math"
    }
   ]
  },
  {
   "title": "AWS S3 Egress Cost Without Alluxio (East -> West)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A+$B) / 1024/1024/1024*0.02", "type": "math" }
   ]
  },
  {
   "title": "AWS S3 Egress Cost With Alluxio (East -> West)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Worker_Client_CacheBytesRequestedExternal_total",
     "legendFormat": "__auto"
    },
    { "expression": "$A /1024/1024/1024*0.02", "type": "math" }
   ]
  },
  {
   "title": "AWS S3 Total Cost Saving",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($A+$B)/1000*0.0004 + $C/1000*0.005+$D/1024/1024/1024*0.02",
     "type": "math"
    }
   ]
  },
  {
   "title": "Datasets and Multi-Tenancy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dataset Management (Future Work)",
     "type": "text",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "options": {
      "content": "| Name     | Cache Capacity | Cache Space Used | Load                                    | Free                         | Pin                   |\n|----------|---------|----|----------------------------|-------------------------------------|-----------------------|\n| Table1   | 100GB | 20GB |[Cache All](https://example.com/item1/free)   | [Cache Footer ](https://example.com/item1/load) | [Cache Fragment](https://example.com/item1/pin) |\n| Table2   | 100GB | 20GB |[Cache All](https://example.com/item2/free)    | [Cache Footer ](https://example.com/item2/load) | [Cache Fragment](https://example.com/item2/pin)  |\n| Table3   | 100GB | 20GB | [Cache All](https://example.com/item3/free)   | [Cache Footer ](https://example.com/item3/load) | [Cache Fragment](https://example.com/item3/pin) |\n"
     }
    },
    {
     "title": "Multi-Tenancy (Future Work)",
     "type": "text",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "options": {
      "content": "| Name     | Cache Capacity | Cache Space Used | Cache All                                    | Cache Footer                              | Cache Fragment                   |\n|----------|---------|----|----------------------------|-------------------------------------|-----------------------|\n| user Danica   | 100GB | 20GB |[Cache All](https://example.com/item1/free)   | [Cache Footer ](https://example.com/item1/load) | [Cache Fragment](https://example.com/item1/pin) |\n| user Jingwen   | 100GB | 20GB |[Cache All](https://example.com/item2/free)    | [Cache Footer ](https://example.com/item2/load) | [Cache Fragment](https://example.com/item2/pin)  |\n| user Bin   | 100GB | 20GB | [Cache All](https://example.com/item3/free)   | [Cache Footer ](https://example.com/item3/load) | [Cache Fragment](https://example.com/item3/pin) |\n"
     }
    },
    {
     "title": "Cache Filter (Future Work)",
     "type": "text",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "options": {
      "content": "| Name     | Cache Capacity | Cache Space Used | Cache All                                    | Cache Footer                              | Cache Fragment                   |\n|----------|---------|----|----------------------------|-------------------------------------|-----------------------|\n| Table1   | 100GB | 20GB |[Cache All](https://example.com/item1/free)   | [Cache Footer ](https://example.com/item1/load) | [Cache Fragment](https://example.com/item1/pin) |\n| Table2   | 100GB | 20GB |[Cache All](https://example.com/item2/free)    | [Cache Footer ](https://example.com/item2/load) | [Cache Fragment](https://example.com/item2/pin)  |\n| Table3   | 100GB | 20GB | [Cache All](https://example.com/item3/free)   | [Cache Footer ](https://example.com/item3/load) | [Cache Fragment](https://example.com/item3/pin) |\n"
     }
    }
   ]
  },
  { "title": "Cache Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Cache Space Used Per Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "Worker_Client_CacheSpaceUsed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cached Space Available Per worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "Worker_Client_CacheSpaceAvailable",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached Pages Per Worker",
   "type": "timeseries",
   "description": "Total number of pages in the client cache",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    { "expr": "Client_CachePages", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Cache Get Error Total Rate",
   "type": "timeseries",
   "description": "Total number of pages in the client cache",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(app) (increase(Worker_Client_CacheGetErrors[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached Pages Per Worker",
   "type": "timeseries",
   "description": "Total number of pages in the client cache",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "targets": [
    { "expr": "Client_CachePages", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Cache Get Error Rate Per Worker ",
   "type": "timeseries",
   "description": "Total number of pages in the client cache",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "increase(Worker_Client_CacheGetErrors[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency & Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "os_cpuLoad", "legendFormat": "{{node}}" }
     ]
    },
    {
     "title": "Os Max File Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "targets": [
      { "expr": "os_maxFileCount", "legendFormat": "{{node}}" }
     ]
    },
    {
     "title": "Os Open File Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "targets": [
      { "expr": "os_openFileCount", "legendFormat": "{{node}}" }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Young GC Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "rate(G1_Young_Generation_count[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Yong GC Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
     "targets": [
      {
       "expr": "increase(G1_Young_Generation_time[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Old GC Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "increase(G1_Old_Generation_time[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Old GC Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
     "targets": [
      {
       "expr": "rate(G1_Old_Generation_count[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}